@echo off
title Fake-RTC Automatic Synchronizer (USB Finder)
chcp 65001 >nul

echo ===================================================
echo     AUTOMATIC TIME SYNCHRONIZER (PC -> USB)
echo ===================================================
echo.
echo [SYSTEM] Searching for USB drive with "time_save.txt" in root...

:: 1. Intelligent loop to scan drive letters from D to Z
set "RUTA_USB="
for %%L in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
    if exist "%%L:\time_save.txt" (
        set "RUTA_USB=%%L:\time_save.txt"
        set "LETRA_DRIVE=%%L"
        goto :ENCONTRADO
    )
)

:: If it scans the entire alphabet and does not find the file
:NO_ENCONTRADO
color 0C
echo [ERROR] No USB drive detected with "time_save.txt" file.
echo Please connect your USB to the computer and try again.
echo.
pause
exit /b

:ENCONTRADO
color 0B
echo [SYSTEM] USB drive successfully detected on drive: %LETRA_DRIVE%
echo [SYSTEM] Fetching precise time from PC...

:: 2. Capture universal date and time from Windows (10/11) in YYYY MM DD HH MM SS format
for /f "tokens=1-6" %%A in ('powershell -Command "Get-Date -Format 'yyyy MM dd HH mm ss'"') do (
    set "ANIO=%%A"
    set "MES=%%B"
    set "DIA=%%C"
    set "HORA=%%D"
    set "MIN=%%E"
    set "SEG=%%F"
)

:: 3. Build the string with the exact format required by Linux
set "FORMATO_FINAL=%ANIO%-%MES%-%DIA% %HORA%:%MIN%:%SEG%"

:: 4. Clean write into the detected USB file without spaces or trailing newlines
<nul set /p="%FORMATO_FINAL%">"%RUTA_USB%"

:: 5. Visual confirmation on screen
color 0A
echo.
echo [SUCCESS] The file on the USB has been updated correctly.
echo [DATA] New recorded time: %FORMATO_FINAL%
echo.

:: =========================================================================
:: [GHOST FILE AUTO-CLEAN SUBROUTINE]
:: =========================================================================
:: Silently deletes the residual file generated by the Batch bug
if exist "%~dp0USB)" del /f /q "%~dp0USB)" 2>nul
if exist "%~dp0usb)" del /f /q "%~dp0usb)" 2>nul
if exist "USB)" del /f /q "USB)" 2>nul
if exist "usb)" del /f /q "usb)" 2>nul
:: =========================================================================

echo You can now safely eject the USB drive and connect it to your console.
echo.
timeout /t 5
